name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Docker
        run: |
          echo "Setting up Docker"
          sudo apt-get update -y
          sudo apt-get install \
             apt-transport-https \
             ca-certificates \
             curl \
             gnupg-agent \
             software-properties-common virtualenv virtualenvwrapper -y
             sudo dpkg-reconfigure --frontend noninteractive tzdata
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository \
             "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
             $(lsb_release -cs) \
             stable"
          sudo apt-get update -y
          sudo apt-get install docker-ce docker-ce-cli containerd.io -y
          sudo curl -L https://github.com/docker/compose/releases/download/1.27.4/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - name: docker build
        run: |
          git clone https://github.com/seconize-co/sze-k8s-pt.git
          cd sze-k8s-pt
          sudo docker-compose up --build
      - name: Docker Push to Azure Container Registry
        run: |
          sudo apt install gnupg2 pass -y
          echo ${{ secrets.ACR_PWD }} | docker login --username seconize --password-stdin seconize.azurecr.io
          sudo docker tag sze-k8s-pt seconize.azurecr.io/sensor/sze-k8s-pt
          sudo docker push seconize.azurecr.io/sensor/sze-k8s-pt
